<?php

namespace App\Controller\Admin;

use App\Entity\Caf;
use App\Entity\Mois;
use Doctrine\ORM\EntityManagerInterface;
use EasyCorp\Bundle\EasyAdminBundle\Controller\AbstractCrudController;
use EasyCorp\Bundle\EasyAdminBundle\Field\AssociationField;
use EasyCorp\Bundle\EasyAdminBundle\Field\CollectionField;
use EasyCorp\Bundle\EasyAdminBundle\Field\DateField;
use EasyCorp\Bundle\EasyAdminBundle\Field\DateTimeField;
use EasyCorp\Bundle\EasyAdminBundle\Field\IdField;
use EasyCorp\Bundle\EasyAdminBundle\Field\NumberField;
use EasyCorp\Bundle\EasyAdminBundle\Field\TextField;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;

class CafCrudController extends AbstractCrudController
{
    public static function getEntityFqcn(): string
    {
        return Caf::class;
    }


    public function configureFields(string $pageName): iterable
    {
        return [
            IdField::new('id')->hideOnForm(),
            TextField::new('titre'),
            NumberField::new('Credit'),
            NumberField::new('Debit'),
            //DateField::new('date_debut'),
            AssociationField::new('id_mois')
        ];
    }

//    public function persistEntity(EntityManagerInterface $entityManager, $entityInstance): void
//    {
//        if(!$entityInstance instanceof Caf){
//           $entityInstance->setCreatedAt(new \DateTimeImmutable);
//        }
//        parent::persistEntity($entityManager, $entityInstance); // TODO: Change the autogenerated stub
//    }
}
